### ISSUE TITLE
More details on worker fail

### ISSUE THREAD

**Issue by yonromai** [spotify/hype#32]
Here is what happens now when a worker crashes:
```
[error] [main] INFO com.spotify.hype.runner.DockerRunner - Kubernetes pod hype-run-ojvmt7xq failed with status PodStatus(conditions=[PodCondition(lastProbeTime=null, lastTransitionTime=2017-04-26T01:45:52Z, message=null, reason=null, status=True, type=Initialized, additionalProperties={}), PodCondition(lastProbeTime=null, lastTransitionTime=2017-04-26T01:46:09Z, message=containers with unready status: [hype-run], reason=ContainersNotReady, status=False, type=Ready, additionalProperties={}), PodCondition(lastProbeTime=null, lastTransitionTime=2017-04-26T01:45:52Z, message=null, reason=null, status=True, type=PodScheduled, additionalProperties={})], containerStatuses=[ContainerStatus(containerID=docker://8a49ba64a77f911bcdc4b614133a562cda29a7324a55be4670562c16daac5066, image=spotify/hype:1, imageID=docker://sha256:67313963c8f79aeb7062ac60a44350278678ad6a351a19b832e171a80ba8e7fd, lastState=ContainerState(running=null, terminated=null, waiting=null, additionalProperties={}), name=hype-run, ready=false, restartCount=0, state=ContainerState(running=null, terminated=ContainerStateTerminated(containerID=docker://8a49ba64a77f911bcdc4b614133a562cda29a7324a55be4670562c16daac5066, exitCode=1, finishedAt=2017-04-26T01:46:08Z, message=null, reason=Error, signal=null, startedAt=2017-04-26T01:45:52Z, additionalProperties={}), waiting=null, additionalProperties={}), additionalProperties={})], hostIP=10.142.0.5, message=null, phase=Failed, podIP=10.4.10.80, reason=null, startTime=2017-04-26T01:45:52Z, additionalProperties={})
[error] Exception in thread "main" java.lang.RuntimeException: Failed to get return value
[error] 	at com.spotify.hype.Submitter.runOnCluster(Submitter.java:166)
[error] 	at com.spotify.hype.HypeSubmitter$class.submit(HypeSubmitter.scala:10)
[error] 	at com.spotify.hype.GkeSubmitter.submit(GkeSubmitter.scala:4)
[error] 	at com.spotify.hyperflo.examples.CrossValInternal$.run(CrossValInternal.scala:52)
[error] 	at com.spotify.hyperflo.examples.CrossValInternal$.main(CrossValInternal.scala:130)
[error] 	at com.spotify.hyperflo.examples.CrossValInternal.main(CrossValInternal.scala)
java.lang.RuntimeException: Nonzero exit code returned from runner: 1
	at scala.sys.package$.error(package.scala:27)
[trace] Stack trace suppressed: run last examples/compile:runMain for the full output.
```
There is not much information here.

When there is no retry policy, it's not possible to access the pod logs because it's gone. The only way is to go to stackdriver and wait for the logs to propagate.

@rgruener  Could there be a way to surface the container logs if it fails, so that they appear in the master's console?

**Comment by rgruener** [comment]
Hmm, surfacing them in the masters console could be possible on failure by writing the stack trace to the termination log. On success the termination log points to the serialized return value, on failure we could perhaps have it point to a stack trace of what went wrong. @rouzwawi thoughts?
