### ISSUE TITLE
Transitive dependencies causing problems with other open source packages

### ISSUE THREAD

**Issue by flylo** [spotify/hype#39]
I use hype in a monorepo that also contains [scio](https://github.com/spotify/scio) pipelines. Hype pulls in a lot of transitive dependencies that cause nasty collisions that I've only been able to work around with exclusions and dependency overrides. Specifically, guava and protobuf have given me the most trouble. I'm not sure what exactly the best way to get around this is, but it would be great if we could make Hype a little more lightweight so that it could play nicer with other scala pipeline tools.

An example error is shown below, where the scio `PubsubClient` is using the `com.google.common.base.Preconditions` that gets packaged with `hype-submitter-0.0.17.jar`:
```
An exception or error caused a run to abort: com.google.common.base.Preconditions.checkState(ZLjava/lang/String;Ljava/lang/Object;)V 
java.lang.NoSuchMethodError: com.google.common.base.Preconditions.checkState(ZLjava/lang/String;Ljava/lang/Object;)V
	at org.apache.beam.sdk.io.gcp.pubsub.PubsubClient$SubscriptionPath.<init>(PubsubClient.java:188)
	at org.apache.beam.sdk.io.gcp.pubsub.PubsubClient.subscriptionPathFromName(PubsubClient.java:238)
	at org.apache.beam.sdk.io.gcp.pubsub.PubsubIO$SubscriptionPathTranslator.apply(PubsubIO.java:289)
	at org.apache.beam.sdk.io.gcp.pubsub.PubsubIO$SubscriptionPathTranslator.apply(PubsubIO.java:284)
	at org.apache.beam.sdk.options.ValueProvider$NestedValueProvider.get(ValueProvider.java:131)
	at org.apache.beam.sdk.io.gcp.pubsub.PubsubUnboundedSource.getSubscription(PubsubUnboundedSource.java:1374)
	at org.apache.beam.sdk.io.gcp.pubsub.PubsubUnboundedSource$PubsubSource.<init>(PubsubUnboundedSource.java:1103)
	at org.apache.beam.sdk.io.gcp.pubsub.PubsubUnboundedSource.expand(PubsubUnboundedSource.java:1407)
	at org.apache.beam.sdk.io.gcp.pubsub.PubsubUnboundedSource.expand(PubsubUnboundedSource.java:110)
	at org.apache.beam.sdk.Pipeline.applyInternal(Pipeline.java:514)
	at org.apache.beam.sdk.Pipeline.applyTransform(Pipeline.java:454)
	at org.apache.beam.sdk.values.PBegin.apply(PBegin.java:44)
	at org.apache.beam.sdk.io.gcp.pubsub.PubsubIO$Read.expand(PubsubIO.java:730)
	at org.apache.beam.sdk.io.gcp.pubsub.PubsubIO$Read.expand(PubsubIO.java:536)
	at org.apache.beam.sdk.Pipeline.applyInternal(Pipeline.java:514)
	at org.apache.beam.sdk.Pipeline.applyTransform(Pipeline.java:473)
	at org.apache.beam.sdk.values.PBegin.apply(PBegin.java:56)
	at org.apache.beam.sdk.Pipeline.apply(Pipeline.java:180)
	at com.spotify.scio.ScioContext.applyInternal(ScioContext.scala:425)
	at com.spotify.scio.ScioContext$$anonfun$pubsubIn$1.apply(ScioContext.scala:657)
	at com.spotify.scio.ScioContext$$anonfun$pubsubIn$1.apply(ScioContext.scala:634)
	at com.spotify.scio.ScioContext.requireNotClosed(ScioContext.scala:382)
	at com.spotify.scio.ScioContext.pubsubIn(ScioContext.scala:633)
	at com.spotify.scio.ScioContext.pubsubSubscription(ScioContext.scala:674)
	at com.spotify.ads.adserver.pipelines.streaming.adrequestservice.AdRequestServiceBQLoggerJob$.main(AdRequestServiceBQLoggerJob.scala:75)
	at com.spotify.ads.adserver.pipelines.streaming.adrequestservice.AdRequestServiceBQLoggerIntegrationTest$$anonfun$1.apply$mcV$sp(AdRequestServiceBQLoggerIntegrationTest.scala:40)
	at com.spotify.ads.adserver.pipelines.streaming.adrequestservice.AdRequestServiceBQLoggerIntegrationTest$$anonfun$1.apply(AdRequestServiceBQLoggerIntegrationTest.scala:26)
	at com.spotify.ads.adserver.pipelines.streaming.adrequestservice.AdRequestServiceBQLoggerIntegrationTest$$anonfun$1.apply(AdRequestServiceBQLoggerIntegrationTest.scala:26)
	at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
	at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
	at org.scalatest.Transformer.apply(Transformer.scala:22)
	at org.scalatest.Transformer.apply(Transformer.scala:20)
	at org.scalatest.FlatSpecLike$$anon$1.apply(FlatSpecLike.scala:1682)
	at org.scalatest.TestSuite$class.withFixture(TestSuite.scala:196)
	at org.scalatest.FlatSpec.withFixture(FlatSpec.scala:1685)
	at org.scalatest.FlatSpecLike$class.invokeWithFixture$1(FlatSpecLike.scala:1679)
	at org.scalatest.FlatSpecLike$$anonfun$runTest$1.apply(FlatSpecLike.scala:1692)
	at org.scalatest.FlatSpecLike$$anonfun$runTest$1.apply(FlatSpecLike.scala:1692)
	at org.scalatest.SuperEngine.runTestImpl(Engine.scala:289)
	at org.scalatest.FlatSpecLike$class.runTest(FlatSpecLike.scala:1692)
	at org.scalatest.FlatSpec.runTest(FlatSpec.scala:1685)
	at org.scalatest.FlatSpecLike$$anonfun$runTests$1.apply(FlatSpecLike.scala:1750)
	at org.scalatest.FlatSpecLike$$anonfun$runTests$1.apply(FlatSpecLike.scala:1750)
	at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:396)
	at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:384)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:384)
	at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:373)
	at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:410)
	at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:384)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:384)
	at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:379)
	at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:461)
	at org.scalatest.FlatSpecLike$class.runTests(FlatSpecLike.scala:1750)
	at org.scalatest.FlatSpec.runTests(FlatSpec.scala:1685)
	at org.scalatest.Suite$class.run(Suite.scala:1147)
	at org.scalatest.FlatSpec.org$scalatest$FlatSpecLike$$super$run(FlatSpec.scala:1685)
	at org.scalatest.FlatSpecLike$$anonfun$run$1.apply(FlatSpecLike.scala:1795)
	at org.scalatest.FlatSpecLike$$anonfun$run$1.apply(FlatSpecLike.scala:1795)
	at org.scalatest.SuperEngine.runImpl(Engine.scala:521)
	at org.scalatest.FlatSpecLike$class.run(FlatSpecLike.scala:1795)
	at org.scalatest.FlatSpec.run(FlatSpec.scala:1685)
	at org.scalatest.tools.SuiteRunner.run(SuiteRunner.scala:45)
	at org.scalatest.tools.Runner$$anonfun$doRunRunRunDaDoRunRun$1.apply(Runner.scala:1340)
	at org.scalatest.tools.Runner$$anonfun$doRunRunRunDaDoRunRun$1.apply(Runner.scala:1334)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at org.scalatest.tools.Runner$.doRunRunRunDaDoRunRun(Runner.scala:1334)
	at org.scalatest.tools.Runner$$anonfun$runOptionallyWithPassFailReporter$2.apply(Runner.scala:1011)
	at org.scalatest.tools.Runner$$anonfun$runOptionallyWithPassFailReporter$2.apply(Runner.scala:1010)
	at org.scalatest.tools.Runner$.withClassLoaderAndDispatchReporter(Runner.scala:1500)
	at org.scalatest.tools.Runner$.runOptionallyWithPassFailReporter(Runner.scala:1010)
	at org.scalatest.tools.Runner$.run(Runner.scala:850)
	at org.scalatest.tools.Runner.run(Runner.scala)
	at org.jetbrains.plugins.scala.testingSupport.scalaTest.ScalaTestRunner.runScalaTest2(ScalaTestRunner.java:138)
	at org.jetbrains.plugins.scala.testingSupport.scalaTest.ScalaTestRunner.main(ScalaTestRunner.java:28)```

**Comment by flylo** [comment]
@jonsondag has been having additional issues with the spotify docker-client dep. There are apparently two version of this, one that shades some dependencies and one that doesn't. Hype pulls in the non-shaded version whereas helios-testing, a necessary dep for our project, pulls in the shaded one. We end up with `NoSuchMethodError`s because the shaded docker client expects a relocated version of guava, but hype is pulling in the non-relocated one.

We need Hype set up such that it relocates transitive dependencies.
